name: Update Branch securely
description: Update Branch securely
author: Shunsuke Suzuki
branding:
  icon: git-commit
  color: green
inputs:
  app_id:
    description: |
      GitHub App ID
    required: true
  app_private_key:
    description: |
      GitHub App Private Key
    required: true
  server_repository_name:
    description: |
      Server repository name
    required: true

  server_repository_owner:
    description: |
      Server repository owner
    required: false
    default: ${{github.repository_owner}}
  repository_owner:
    description: The repository owner of the updated pull request
    required: false
    default: ${{github.repository_owner}}
  repository_name:
    description: The repository name of the updated pull request
    required: false
    default: ${{github.event.repository.name}}
  pull_request_number:
    description: |
      Pull request numbers of the updated pull requests.
      You can specify multiple pull request numbers separated by commas or newlines.
    required: false
    default: ${{github.event.issue.number}}
runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/index.js"
