name: Update Branch securely
description: Update Branch securely
author: Shunsuke Suzuki
branding:
  icon: git-commit
  color: green
inputs:
  app_id:
    description: |
      GitHub App ID
    required: true
  app_private_key:
    description: |
      GitHub App Private Key
    required: true
  server_repository_name:
    description: |
      Server repository name
    required: true

  server_repository_owner:
    description: |
      Server repository owner
    required: false
    default: ${{github.repository_owner}}
  repository_owner:
    description: The repository owner of the updated pull request
    required: false
    default: ${{github.repository_owner}}
  repository_name:
    description: The repository name of the updated pull request
    required: false
    default: ${{github.event.repository.name}}
  pull_request_number:
    description: |
      The pull request number of the updated pull request
    required: false
    default: ${{github.event.issue.number}}
runs:
  using: composite
  steps:
    # Create a GitHub App token to create and delete a label
    - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
      id: token
      with:
        app-id: ${{inputs.app_id}}
        private-key: ${{inputs.app_private_key}}
        permission-issues: write
        owner: ${{ inputs.server_repository_owner }}
        repositories: |
          ${{inputs.server_repository_name}}

    - uses: securefix-action/label-action@c6acf8ab33ab3b904781d7aabd39b72543791b88 # v0.0.2
      with:
        prefix: update-branch-
        description: ${{inputs.repository_owner}}/${{inputs.repository_name}}/${{inputs.pull_request_number}}
        repository_owner: ${{inputs.server_repository_owner}}
        repository_name: ${{inputs.server_repository_name}}
        github_token: ${{steps.token.outputs.token}}
